version: 1.0.{build}
image: Visual Studio 2019

# Настройка языка программирования
environment:
  nodejs_version: "16"

# Настройка сборки
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

build_script:
  - npm run build

artifacts:
  - path: dist
    name: MyApp

# Настройка деплоя
deploy:
  provider: GitHub
  release: $(appveyor_build_version)
  artifact: MyApp.zip
  auth_token:
    secure: $(auth_token)
